name: Build Executables for Version 2

on:
  push:
    branches:
      - main  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.1'  # Use a valid Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Navigate to v2 folder
        run: cd v2

      - name: Build executable for v3
        run: |
          pyinstaller --onefile app.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: ${{ runner.os }}-v2-executable
          path: v2/dist/